#configuration of department service inside the config-server
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#everything of traces should be published to zipkin server
management:
  tracing:
    sampling:
      probability: 1.0